# 1. Ignora absolutamente tudo na raiz do projeto
**/*

# 2. Libera APENAS o que o serviço do tibiagame precisa
!/docker/tibiagame/script
!/docker/tibiagame/patches
!/files/game
!/files/dennis-libraries
!/files/tibiagame/.tibia
!/files/tibiagame/save
!/files/tibiagame/npc
!/files/tibiagame/bin
!/files/tibiagame/doc
#!/files/tibiagame/log
!/files/tibiagame/mon
!/files/tibiagame/dat
